### ISSUE TITLE
Remove replicated initial condition from `states` list in test configurations

### ISSUE THREAD

**Issue by twsearle** [MetOffice/orca-jedi#43]
## Description

We discovered that the initial condition and the first entry in the states list are both passed to `oops::GetValues::apply`. This means that time interpolation is attempted between two identical states. This does no damage in this case, however it is confusing and possibly incurs a small performance hit.

Provided we receive confirmation that the initial state should not be replicated in the first entry in the states list (in JCSDA-internal/oops#2243), we will need to update the orca-jedi tests and the sith yaml configurations to account for this.

There will also be an impact on sith. I have had a go at a change here:
http://fcm9/projects/utils/browser/ocean_obs_processing_apps/branches/dev/tsearle/r34276_no_initial_condition_in_states
But I will likely need to make a ticket to cover this issue in that repo.

## Acceptance Criteria (Definition of Done)

ctests and sith still pass

## Dependencies

JCSDA-internal/oops#2243

**Comment by tom-j-h** [comment]
This can be closed, right @twsearle? https://github.com/MetOffice/orca-jedi/pull/73. My bad if so!

**Comment by twsearle** [comment]
Ahh yes sorry!  I guess the issue and the PR didn't link properly closing it now. Let me know if you need anything else though.

**Comment by tom-j-h** [comment]
Thank you, all good for now!
